version: '3.9'

services:
  app: &app
    image: vche-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=webpack"
    volumes:
      - .:/vche
      - app_bundler:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  webpack:
    <<: *app
    command: "bin/webpack-dev-server"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"
    ports:
      - "3035:3035"
    depends_on:
      - app
    tty: false
    stdin_open: false
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_mysql:/var/lib/mysql

volumes:
  app_bundler:
    driver: local
  db_mysql:
    driver: local
