version: '3.9'

# docker-compose is for development

services:
  app: &app
    image: vche-rails-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      RAILS_ENV: development
      VCHE_ENV: local
      WEBPACKER_DEV_SERVER_HOST: webpack
      VCHE_SOCKET: "tcp://0.0.0.0:3000"
    volumes:
      - .:/vche
      - app_bundler-dev:/usr/local/bundle
      - app_node_modules-dev:/vche/node_modules
      - app_tmp_cache-dev:/vche/tmp/cache
      - app_tmp_pids-dev:/vche/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  webpack:
    <<: *app
    command: "bin/webpack-dev-server"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"
    ports:
      - "3035:3035"
    depends_on:
      - app
    stdin_open: true
    tty: true
    entrypoint:
      - "prehook"
      - "yarn"
      - "--"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_mysql-dev:/var/lib/mysql

volumes:
  app_bundler-dev:
    driver: local
  app_node_modules-dev:
    driver: local
  app_tmp_cache-dev:
    driver: local
  app_tmp_pids-dev:
    driver: local
  db_mysql-dev:
    driver: local
