name: Vche-rails
on: [push]
jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
        working-directory: ./Vche-rails
      - run: bundle exec rubocop --parallel
        working-directory: ./Vche-rails

