name: Vche-rails
on: [push]
defaults:
  run:
    working-directory: ./Vche-rails
jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - run: bundle exec rubocop --parallel
